Algoritmo "exemplo_12"

Var

nome : caractere
valor : real
hora : real
pagamento : real


Inicio

nome <- "Joao Slva"
valor <- 50
hora <- 60
pagamento <- 60 * 50


escreval ("nome : Joao Silva")
escreval
escreval ("O Valor da hora trabalhada pelo funcionario equivale a ", 50, " reais")
escreval
escreval ("O funcionario trabalhou ",60 ," horas no mes")
escreval
escreval ("O pagamento para joao Silva deve ser ", 60 * 50)


Fimalgoritmo